version: "3"
services:
  envoy_proxy:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/envoy-proxy
    volumes:
    - ./config/envoy-proxy-config.yml:/etc/envoy-proxy-config.yaml
    - ./config/start-envoy.sh:/etc/start-envoy.sh
    - ./config/hot-restarter.py:/etc/hot-restarter.py
    ports:
    - "9901:9901"

  xds_server:
    build:
      context: .
      dockerfile: ./dockerfiles/xds-server
    ports:
    - "5678:5678"
    - "4678:4678"
